cookie: e2e=55B2D1619F0C8CF273169F8F1CA49A93; e2mf=79921c4a53e34001ba1dc78d7c03e188; token=79921c4a53e34001ba1dc78d7c03e188
tikutoken: 732FD8402F95087CD934374135C46EE5
toml_folder: output_toml
# llm_api_key: sk-qWiF3AUQXgnUuhgZhMN0LvLFbY6J0j8FfLmo70Txx5zH3uq9
# llm_api_base_url: https://api.tu-zi.com/v1
# llm_model_name: gemini-3-flash-preview

llm_api_key: 26e96c4d312e48feacbd78b7c42bd71e
llm_api_base_url: http://menshen.xdf.cn/v1
llm_model_name: gemini-3.0-pro-preview

